### 1. Import Libraries

In [1]:
import os
import sys
import warnings

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from sklearn.datasets import fetch_openml
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

%matplotlib inline
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

### 2. Import from mlcblab

In [2]:
from mlcvlab.models.nn1 import NN1
from mlcvlab.models.nn2 import NN2
from mlcvlab.nn.losses import l2
from mlcvlab.optim.sgd import SGD
from mlcvlab.optim.adam import Adam

### 3. Set Seed

In [3]:
np.random.seed(42)

### 4. Helper functions

In [4]:
def load_dataset():
    #TODO
    x, y = fetch_openml("mnist_784", version=1, return_X_y=True, as_frame=False)
    return x,y

def prepare_data(x, y):
    #TODO
    y=y.astype(np.int16)
    for i in range(len(y)):
        y[i]=1 if y[i]%2==0 else 0
    return x, y

def split_train_test(x,y):
    #TODO
    X_train, X_test, y_train, y_test=train_test_split(x,y,test_size=10000)
    return X_train, X_test, y_train, y_test

def initialize_model(X_train, X_test, y_train, y_test):
    #TODO
    W0 = None
    W1 = None
    two_layer_nn  = NN2()
    # two_layer_nn.W = [W0, W1]
    # two_layer_nn.layers[0].W = W0
    # two_layer_nn.layers[1].W = W1
    print(f"Size of W0 : {two_layer_nn.W[0]}, Size of W1 : {two_layer_nn.W[1][0].shape}")
    return two_layer_nn

def train_model(model, X_train, y_train):
    final_W  = None

    #TODO : Call SGD or Adam optimizer to train model.
    SGD(model, X_train, y_train, lr=0.1)
    # Adam(model,X_train,y_train)    
    return final_W

def test_model(model, X_test, y_test, final_W):
    accuracy = None
    model.W = final_W
    y_hat=model.nn2(X_test)
    y_hat_mod=1*(y_hat>=0.5)
    
    accuracy=np.sum(np.abs(y_hat_mod-y_test))/10000
    
    #TODO: Call model.nn2 to test model.
    return accuracy

### 5. Run the program

In [5]:
#load data
x, y = load_dataset()

#prepare data
x, y = prepare_data(x,y)

# split data set
X_train, X_test, y_train, y_test = split_train_test(x,y)

In [6]:
#initialize model
model = initialize_model(X_train, X_test, y_train, y_test)

#training model
final_W = train_model(model, X_train, y_train)
print(f"Completed training model - final W : {final_W}")


#testing model
accuracy = test_model(model, X_test, y_test, final_W)
print(f"Completed testing model - Accuracy : {accuracy}")    

Size of W0 : [[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]], Size of W1 : (500,)
(500, 784)


ValueError: shapes (1,500) and (60000,500) not aligned: 500 (dim 1) != 60000 (dim 0)